version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 3
    groups:
      root-aws-sdk:
        patterns:
          - "@aws-sdk/*"
        update-types:
          - "minor"
          - "patch"
      root-react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "minor"
          - "patch"
      root-remaining:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react-dom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@types/react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@types/react-dom"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/infra"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 3
    groups:
      infra-aws-sdk:
        patterns:
          - "@aws-sdk/*"
        update-types:
          - "minor"
          - "patch"
      infra-types:
        patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      infra-remaining:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "actions/checkout"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "actions/setup-python"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "actions/github-script"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "actions/upload-artifact"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "aws-actions/configure-aws-credentials"
        update-types:
          - "version-update:semver-major"
