version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/vnext"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 3
    groups:
      vnext-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "actions/*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "astral-sh/setup-uv"
        update-types:
          - "version-update:semver-major"
